### ISSUE TITLE
TMNF- Impression site expired ssl cert.

### ISSUE THREAD

**Issue by sebasdt** [nils-ost/TMNF-TimeAttackServer#3]
Hi,
Just wanted to let you know your TMNF tas Impression site SSL certificate expired for a while.
The cert hasn't been valid since Sun, 18 Jun 2023 00:31:10 GMT
https://nijos.de/tmnf-timeattackserver/tmnf-tas-impressions/

It would be better for your site to renew it ;)

Good luck!

**Comment by nils-ost** [comment]
thanks, the auto-renew didn't work as expected. Just invoked a renewal ;) Should be valid soon again :)
