### ISSUE TITLE
Where can I increase the time per track?

### ISSUE THREAD

**Issue by sebasdt** [nils-ost/TMNF-TimeAttackServer#5]
Hi!
Here am i again!
Was wondering how I can increase the race time or is it possible to dynamically adjust the time per track?
looked around in the matchsettings changed it there, after a reboot it seems like time was reset back.

**Comment by nils-ost** [comment]
Hi,
This can be done in the config.json of tmnf-tas

You can read about it here:
https://github.com/nils-ost/TMNF-TimeAttackServer/blob/master/docs/configuration.md
It's in the section advanced -> TMNF-TAS -> config.json

The parameter is: least_time in the challenges dict

Regards Nils

**Comment by sebasdt** [comment]
next time for me RTFM xd. anyway, thank you!
